// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2906.SentinelSteamworks.subsystems;

import org.usfirst.frc2906.SentinelSteamworks.RobotMap;
import org.usfirst.frc2906.SentinelSteamworks.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearMech extends Subsystem {

    private final DoubleSolenoid piston = RobotMap.GearSinglePiston;
    private final DoubleSolenoid doublePiston = RobotMap.GearDoublePiston;

    public void initDefaultCommand() {

    }
    
    public void GearRelease(){
    	piston.set(Value.kForward);
    }
    
    public void GearHold(){
    	piston.set(Value.kReverse);
    }
    
    public void GearMechOut(){
    	doublePiston.set(Value.kForward);
    }
    
    public void GearMechIn(){
    	doublePiston.set(Value.kReverse);
    }
}

